### ISSUE TITLE
checker board

### ISSUE THREAD

**Issue by NathanSalapat** [DonBatman/myboardgames#1]
The blocks that make up the checker board are too easily broken which leads to accidental griefing. I don't think they should be protected blocks at all, but maybe they shouldn't be breakable by hand so people don't accidentally break those blocks when moving their playing pieces.

Also might you consider making a check we playing the playing pieces so they can only place on the correct color squares?

**Comment by DonBatman** [comment]
I will fix the blocks breaking. If people use this on a server then they should use a protection mod to keep it from breaking. 
I never thought of doing a check for the right color block. I do not think I will do that because kids like to make up their own games. Good thought though

**Comment by NathanSalapat** [comment]
I checked and the chess board has the same problem, and it looks like both use their own nodes, though I'm guessing the code is probably exactly the same.

I also noticed that the connect4 game requires you to use pickaxe to get the tokens, not sure if that was intentional or not.

**Comment by DonBatman** [comment]
Connect 4 should have been dig immediate by hand. I am very busy today so I won't get to it until tomorrow. Thanks for checking it out. It's great to get feed back and you are good at testing.

**Comment by NathanSalapat** [comment]
Well Lightonflux submitted a mod review request for this mod on my website
so I was just checking it out so I don't try and record a video about
something I don't know about. It won't be recorded until next week so I
thought I'd point out a few of the things I thought were bugs so they could
get fixed before I record my video.

**Comment by DonBatman** [comment]
I will let you know when I get them fixed.

**Comment by DonBatman** [comment]
I forgot to remove dig_immediate from the board pieces. I set it that way for building. It is fixed now.
Dig immiediate was set to 1 instead of 3 for the connect 4 pieces. 

These are fixed now. Thanks for your help.
